### ISSUE TITLE
Opening the menu without needing to hold F3

### ISSUE THREAD

**Issue by TheUnknownBreeze** [ToBinio/useful-saved-hotbars#1]
The mod works wonderfully. However i do find it a bit too much to keep my finger on f3, whilst i choose what i want to load or save.
I would like to make a suggestion towards adding a potential toggle or option (either by config or just an ingame command) to make it so that the screen opens only by pressing f3.
Making it also toggleable would be really useful too, that way you could click once and not hold the key entirely whilst you choose.

**Comment by ToBinio** [comment]
so the workflow you would suggest is:
press f3 + f5/f6 -> menu opens
with f5/f6 you can choose what you want to select
and pressing f3 again would close the menu and do the action?

in my opinion, this would feel a bit clunky 

what would you think about adding another key that opens the menu into a mouse-focused workflow
so you press some key to open the menu and by clicking on a row you run the action

so similar to the inventor

**Comment by TheUnknownBreeze** [comment]
I dont* think you got my idea right (i read it again and i realized i messed up explaining it, probably cuz i made this issue at a late hour)

i've got a little image i made to explain what i was trying to say a bit better
![image](https://github.com/ToBinio/useful-saved-hotbars/assets/97960984/e59c53ff-5260-49fd-a58c-6f3cce0284c2)

**Comment by ToBinio** [comment]
about idea 1:
where you only need to press f6/f7 once to open the menu
would pressing it again select the next row, like right now?
or would it close the menu and run the action?

since right now you finish the action by letting go of f3 and select the next row by pressing f6/f7
and by only using one key you would lose one of those functionalities.

that's why I suggested selecting a row by clicking with the mouse, since this would simplify both interactions


about idea 2:
what do you mean by "or select a toolbar" what user interaction would that be?
pressing f3 again if so, isn't that what I described?  

> press f3 + f5/f6 -> menu opens
> with f5/f6 you can choose what you want to select
> and pressing f3 again would close the menu and do the action?


btw, thanks for your interest in the mod!

**Comment by TheUnknownBreeze** [comment]
as for idea 1:
im suggesting making f6/f7 a singular key to open the menu, simply letting go of the key itself acts as letting go of f3.
you could probably select other bars using the other key, f7/f6 or just the arrow keys.
as for idea 2:
selecting a toolbar from the gui in the save or load state.
this may help a bit for idea 2
> press f3 + f6/f7 (not hold)
utilize the menu while not holding the key
menu closes with the same way used to open it, or esc

(i love saving custom items, so any sort of mod that messes with this stuff is instantly loved by me lol.)

**Comment by ToBinio** [comment]
I think my preferred solution would be a combination of those 2

adding 2 new keys (possibly rebound to f6/f7) that on press open the menu
so single key no holding

pressing the key again would close the menu and run the action.
alternatively, you could also click with the mouse

by clicking the other key, or by using the mouse you can select the row

thoughts?

I don't really want to add some config menu or have some obscure config file, that's why I would simply add 2 new keys (by default unbound) that you can bind to whatever, and unbound the current ones if you don't want them

are you already using 1.21?
or do I have to backport it (if you need it I will happily do it)?

**Comment by TheUnknownBreeze** [comment]
i'm pretty sure we're all good now.
i can understand not having a config, and i do see what you mean
(I am using 1.21, i would suggest backporting it. but thats entirely your choice to do.)
(thanks for responding to the suggestion!)

**Comment by ToBinio** [comment]
just released a new [version 0.2.0](https://modrinth.com/mod/useful-saved-hotbars/version/0.2.0+mc1.21.0)

with the new mode, I made it the default since it feels a lot better to use (thanks for the suggestion)
